# Author: Rich Gibbs, NOAA, NWS, Office of Water Prediction, National Water Center

import batchMosaic as bm
import cleanup

workdir = #change to relevant working directory
attribute = # attribute: 'LAI' or 'FVC'
year = #input year ie '2002'

cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '001')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '009')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '017')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '025')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '033')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '041')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '049')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '057')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '065')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '073')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '081')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '089')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '097')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '105')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '113')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '121')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '129')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '137')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '145')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '153')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '161')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '169')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '177')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '185')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '193')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '201')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '209')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '217')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '225')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '233')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '241')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '249')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '257')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '265')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '273')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '281')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '289')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '297')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '305')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '313')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '321')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '329')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '337')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '345')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '353')
cleanup.del_files(workdir)
bm.mosaic_tif(workdir, attribute, year, '361')
cleanup.del_files(workdir)