# Proposed basin attribute workflows

## ID
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| identifier  | gauge_id             | catchment identifier (eight-digit USGS hydrologic unit code)                                | HDCN-2009                                                                | -       | -                                                                                                                                                       | Reference Fabric POIs                                          | -                          |
| identifier  | HUC2                 | region (two-digit USGS hydrologic unit code)                                                | NHDPlusV2/WBD                                                            | -       | -                                                                                                                                                       | Reference Fabric VPUs                                          | VPU                        |
| identifier  | gauge_name           | gauge name, followed by the state                                                           | HDCN-2009                                                                | -       | -                                                                                                                                                       | Mainstem ID                                                    | -                          |
| identifier  | gauge_lat            | gauge latitude                                                                              | HDCN-2009                                                                | -       | -                                                                                                                                                       | Outlet X                                                       | -                          |
| identifier  | gauge_long           | gauge longitude                                                                             | HDCN-2009                                                                | -       | -                                                                                                                                                       | Outlet Y                                                       | -                          |

## Climatology
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| climatology | p_mean               | mean daily precipitation                                                                    | N15 Daymet 1km Daily - 1 October 1989 to 30 September 2009               | mm/day  | basin mean                                                                                                                                              | Gridmet 4km PR                                                 | basin mean                 |    
| climatology | pet_mean             | mean daily PET                                                                              | N15 using Priestley–Taylor formulation calibrate=d for each catchment    | mm/day  | basin mean                                                                                                                                              | Gridmet 4km PET                                                | basin mean                 |
| climatology | p_seasonality        | seasonality and timing of precipitation                                                     | N15 Daymet 1km Daily                                                     | -       | estimated using sine curves to represent the annual temperature and precipitation cycles w/ Eq. (14) in Woods et al. (2009) | Gridmet  4km Daily        | Eq. (14) in Woods et al. (2009)                                | -                           |
| climatology | frac_snow            | fraction of precipitation falling as snow                                                   | N15 Daymet 1km Daily                                                     | -       | basin mean                                                                                                                                              | Gridmet 4km PR / Jennings                                      | basin mean                 |
| climatology | aridity              | aridity                                                                                     | N15 Daymet 1km Daily [`pet_mean`/`p_mean`]                               | -       | basin mean - ratio of mean PET to mean precipitation                                                                                                    | Gridmet  4km Daily                                             | basin mean                 |
| climatology | high_prec_freq       | frequency of high precipitation days                                                        | N15 Daymet 1km Daily                                                     | days/yr | basin mean - greater or equal to 5 times mean daily PPT                                                                                                 | Gridmet  4km Daily                                             | basin mean                 |
| climatology | high_prec_dur        | average duration of high precipitation days                                                 | N15 Daymet 1km Daily                                                     | days    | basin mean                                                                                                                                              | Gridmet  4km Daily                                             | basin mean                 | 
| climatology | high_prec_timing     | season during which most high precipitation days                                            | N15 Daymet 1km Daily                                                     | season  | basin mean - greater or equal to 5 times mean daily PPT                                                                                                 | Gridmet  4km Daily                                             | basin mean                 |
| climatology | low_prec_freq        | frequency of low precipitation days                                                         | N15 Daymet 1km Daily                                                     | days/yr | basin mean - less them 1 mm daily PPT                                                                                                                   | Gridmet  4km Daily                                             | basin mean                 |
| climatology | low_prec_dur         | average duration of low precipitation days                                                  | N15 Daymet 1km Daily                                                     | days    | basin mean - less them 1 mm daily PPT                                                                                                                   | Gridmet  4km Daily                                             | basin mean                 | 
| climatology | low_prec_timing      | season during which most low precipitation days                                             | N15 Daymet 1km Daily [`pet_mean`/`p_mean`]                               | season  | basin mean - less them 1 mm daily PPT                                                                                                                   | Gridmet  4km Daily                                             | basin mean                 |

## Geology
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| geology     | geol_1st_class       | most common geologic class in the catchment                                                 | Hartmann and Moosdorf (2012) - GLiM                                      | -       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                           |
| geology     | glim_1st_class_frac  | fraction of the catchment area associated with its most common geologic class               | Hartmann and Moosdorf (2012) - GLiM                                      | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                 |
| geology     | geol_2nd_class       | second most common geologic class in the catchment                                          | Hartmann and Moosdorf (2012) - GLiM                                      | -       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean               |
| geology     | glim_2nd_class_frac  | fraction of the catchment area associated with its second most common geologic class        | Hartmann and Moosdorf (2012) - GLiM                                      | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                 |
| geology     | carbonate_rocks_frac | fraction of the catchment area characterized as “carbonate sedimentary rocks”               | Hartmann and Moosdorf (2012) - GLiM                                      | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                 |
| geology     | geol_porostiy        | subsurface porosity|Gleeson et al. (2014)                                                   | GLHYMPS                                                                  | -       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                 |
| geology     | geol_permeability    | subsurface permeability (log10)|Gleeson et al. (2014)                                       | GLHYMPS                                                                  | sq. m   | basin geometric mean                                                                                                                                    | CONUS Soils                                                    | basin geometric mean  |

## Soils
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| soils       | soil_depth_pelletier | depth to bedrock (maximum 50 m)                                                             | Pelletier et al. (2016)                                                  | m       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                           |
| soils       | soil_depth_statsgo   | soil depth                                                                                  | Miller and White (1998) – STATSGO                                        | m       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                           |
| soils       | soil_porosity        | volumetric porosity                                                                         | Miller and White (1998) – STATSGO                                        | -       | basin mean - volumetric porosity (saturated volumetric water content estimated using a multiple linear regression based on sand and clay fraction for the layers marked as USDA soil texture class and a default value (0.9) for layers marked as organic material; layers marked as water, bedrock, and “other” were excluded) - Table 4 in Cosby etal. (1984); Lawrence and Slater (2008)| CONUS Soils ||
| soils       | soil_conductivity    | saturated hydraulic conductivity                                                            | Miller and White (1998) – STATSGO                                        | cm/h    | basin mean - estimated using a multiple linear regression based on sand and clay fraction for the layers marked as USDA soil texture class and a default value (36 cm h) Table 4 in Cosby etal. (1984); Lawrence and Slater (2008)    | CONUS Soils                         |
| soils       | max_water_content    | maximum water content                                                                       | Miller and White (1998) – STATSGO                                        | %       | basin mean - combination of porosity and soil_depth_statsgo; layers marked as water, bedrock, and “other” were excluded                                 | CONUS Soils                                                    | basin mean                           |
| soils       | sand_frac            | sand fraction                                                                               | Miller and White (1998) – STATSGO                                        | %       | basin mean - % of soil material smaller than 2 mm;layers marked as organic material, water, bedrock, and “other” were excluded                          | CONUS Soils                                                    | basin mean                           |
| soils       | clay_frac            | clay fraction                                                                               | Miller and White (1998) – STATSGO                                        | %       | basin mean - % of soil material smaller than 2 mm; layers marked as organic material, water, bedrock, and “other” were excluded                         | CONUS Soils                                                    | basin mean                           |
| soils       | water_frac           | fraction of the top 1.5 m marked as water (class 14)                                        | Miller and White (1998) – STATSGO                                        | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                           |
| soils       | organic_frac         | fraction of soil_depth_statsgo marked as organic material (class 13)                        | Miller and White (1998) – STATSGO                                        | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean                           |
| soils       | other_frac           | fraction of soil_depth_statsgo marked as “other” (class 16)                                 | Miller and White (1998) – STATSGO                                        | %       | basin mean                                                                                                                                              | CONUS Soils                                                    | basin mean 

## Terrain
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| terrain     | area                 | catchment area                                                                              | DEM                                                                      | sq.km   | basin sum                                                                                                                                               | 3DEP 30-m                                                      | basin sum                           |
| terrain     | slope_mean           | catchment mean slope                                                                        | DEM                                                                      | m/km    | basin mean                                                                                                                                              | 3DEP 30-m                                                      | basin mean                          |
| terrain     | elev_mean            | catchment mean elevation                                                                    | DEM                                                                      | m       | basin mean                                                                                                                                              | 3DEP 30-m                                                      | basin mean                        |
===
## Landcover
| Class       | Variable             | Data Description                                                                            | Data Source                                                              | units   | Summary Function Description                                                                                                                            | Proposed Source                                                | Proposed Summary           | 
|-------------|----------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------|----------------------------|
| landcover   | frac_forest          | forest fraction                                                                             | N15 – USGS data (NLCD ####)                                              | %       | basin mean                                                                                                                                              | NLCD 2019                                                      | basin mean                           |
| landcover   | dom_land_cover       | dominant land cover (Noah-modified 20-category IGBP-MODIS land cover)                       | MODIS*                                                                   | -       | basin mode                                                                                                                                              | IGBP-MODIS land cover                                          | basin mode                            |
| landcover   | dom_land_cover_frac  | fraction of the catchment area associated with the dominant land cover                      | MODIS*                                                                   | %       | basin mean                                                                                                                                              | IGBP-MODIS land cover                                          | basin mode                           |
| landcover   | lai_max              | maximum monthly mean of the leaf area index                                                 | MODIS 1k 2002-2014                                                       | -       | remap noah tbl to mod LC, mean of max - based on 12 monthly means                                                                                       | GLASS                                                          | basin mean                           |
| landcover   | lai_diff             | difference between the maximum and minimum monthly mean of the leaf area index              | MODIS*                                                                   | -       | based on 12 monthly means                                                                                                                               | GLASS                                                          | basin mean                           |
| landcover   | gvf_max              | maximum monthly mean of the green vegetation fraction                                       | MODIS*                                                                   | -       | based on 12 monthly means                                                                                                                               | GLASS                                                          | basin mean                           |
| landcover   | gvf_diff             | difference between the maximum and minimum monthly mean of the green vegetation fraction    | MODIS*                                                                   | -       | based on 12 monthly means                                                                                                                               | GLASS                                                          | basin mean                           |
| landcover   | root_depth_XX        | root depth percentiles (XX = 50 and 99%)                                                    | IGBP landcover                                                           | m       | remap noah tbl to mod LC - Eq. (2) and Table 2 in Zeng (2001), basin mean                                                                               | GLASS                                                          | basin mean           
